In [2]:
import torch
import matplotlib.pyplot as plt
from torch import nn



In [3]:
# Create know parameters
weights = 0.7
bias = 0.3

# create data
start = 0
end = 10
step = 0.2

x = torch.arange(start, end, step).unsqueeze(dim=1)
y = weights * x + bias

In [4]:
x[:10], y[:10]

(tensor([[0.0000],
         [0.2000],
         [0.4000],
         [0.6000],
         [0.8000],
         [1.0000],
         [1.2000],
         [1.4000],
         [1.6000],
         [1.8000]]),
 tensor([[0.3000],
         [0.4400],
         [0.5800],
         [0.7200],
         [0.8600],
         [1.0000],
         [1.1400],
         [1.2800],
         [1.4200],
         [1.5600]]))

In [5]:
train_split = int(0.8 * len(x))
X_train, y_train = x[:train_split], x[:train_split]
X_test, y_test = y[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test),len(y_test)

(40, 40, 10, 10)

In [6]:
## Linear Regression from scratch

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float))
        self.bias = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float))

# Forward method to find the computation in the model
    def forward (self, x):
        return self.weights * x + self.bias



# pytorch model building classes

* torch.nn - contain all of the buildings for computational graphs(a another word for neural networks)
* torch.nn parameter = what parameters  should our model try and learn, often a pytroch layer from torch.nn will set these for us
* torch.nn.Module - the base class for all neuaral netwoks it,

In [7]:
# create a random seed

torch.manual_seed(42)

# create an instance of the model (this is a subclass of nn.Module)

model= LinearRegressionModel()

list(model.parameters())

[Parameter containing:
 tensor([0.8823], requires_grad=True),
 Parameter containing:
 tensor([0.9150], requires_grad=True)]

In [8]:
model.state_dict()

OrderedDict([('weights', tensor([0.8823])), ('bias', tensor([0.9150]))])

In [9]:
# setub a loss function
loss_fn = nn.L1Loss()

# setup an optimizer (stochastic gradient descent)
optimizer = torch.optim.SGD(params=model.parameters(), lr=0.001)

### building a training loop and testing loop
* Loop through the data
* forward pass - also called forward propagation
* calculate the loss
* optimizer zero grad
* loss backward - calculate the gradient of each parameters **backpropagation**
* optimzer step - **gradient descent**

In [10]:
epochs = 200

epoch_count = []
loss_values = []
test_loss_values = []

### training 
## 1.Loop through the data
for epoch in range(epochs):

    # set the model to training mode
    model.train()

    # Forward pass
    y_pred = model(X_train)

    #calculate the loss
    loss_value = loss_fn(y_pred, y_train)
 

    # optimizer zer grad

    optimizer.zero_grad()

    # performed backpropagation
    loss_value.backward()

    # step the optimzer
    optimizer.step()


    model.eval()     # turn off different settings in the model not needed for evaluating/testing

    with torch.inference_mode():
        # 1. do the forward
        test_pred = model(X_test)

        # 2. calculating the loss

        test_loss = loss_fn(test_pred, y_test)

    if epoch % 10 == 0:
        epoch_count.append(epoch)
        loss_values.append(loss_value)
        test_loss_values.append(test_loss)
        print(f"Epoch: {epoch} | Test : {loss_value} | Test loss: {test_loss}")


    

Epoch: 0 | Test : 0.4560187757015228 | Test loss: 0.1223519816994667
Epoch: 10 | Test : 0.3958054482936859 | Test loss: 0.051641084253787994
Epoch: 20 | Test : 0.38337674736976624 | Test loss: 0.08508453518152237
Epoch: 30 | Test : 0.37861353158950806 | Test loss: 0.11507654190063477
Epoch: 40 | Test : 0.376332551240921 | Test loss: 0.1300235241651535
Epoch: 50 | Test : 0.3740514814853668 | Test loss: 0.14497017860412598
Epoch: 60 | Test : 0.37219512462615967 | Test loss: 0.14676980674266815
Epoch: 70 | Test : 0.3704783022403717 | Test loss: 0.14669117331504822
Epoch: 80 | Test : 0.3687562942504883 | Test loss: 0.14661264419555664
Epoch: 90 | Test : 0.3670310378074646 | Test loss: 0.14465585350990295
Epoch: 100 | Test : 0.3653142750263214 | Test loss: 0.1445775032043457
Epoch: 110 | Test : 0.36359554529190063 | Test loss: 0.14449873566627502
Epoch: 120 | Test : 0.3618670105934143 | Test loss: 0.14254216849803925
Epoch: 130 | Test : 0.36015012860298157 | Test loss: 0.14246335625648499
E

In [11]:
epoch_count

[0,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190]

In [12]:
loss_values

[tensor(0.4560, grad_fn=<MeanBackward0>),
 tensor(0.3958, grad_fn=<MeanBackward0>),
 tensor(0.3834, grad_fn=<MeanBackward0>),
 tensor(0.3786, grad_fn=<MeanBackward0>),
 tensor(0.3763, grad_fn=<MeanBackward0>),
 tensor(0.3741, grad_fn=<MeanBackward0>),
 tensor(0.3722, grad_fn=<MeanBackward0>),
 tensor(0.3705, grad_fn=<MeanBackward0>),
 tensor(0.3688, grad_fn=<MeanBackward0>),
 tensor(0.3670, grad_fn=<MeanBackward0>),
 tensor(0.3653, grad_fn=<MeanBackward0>),
 tensor(0.3636, grad_fn=<MeanBackward0>),
 tensor(0.3619, grad_fn=<MeanBackward0>),
 tensor(0.3602, grad_fn=<MeanBackward0>),
 tensor(0.3584, grad_fn=<MeanBackward0>),
 tensor(0.3567, grad_fn=<MeanBackward0>),
 tensor(0.3550, grad_fn=<MeanBackward0>),
 tensor(0.3533, grad_fn=<MeanBackward0>),
 tensor(0.3515, grad_fn=<MeanBackward0>),
 tensor(0.3498, grad_fn=<MeanBackward0>)]

In [13]:
test_loss_values

[tensor(0.1224),
 tensor(0.0516),
 tensor(0.0851),
 tensor(0.1151),
 tensor(0.1300),
 tensor(0.1450),
 tensor(0.1468),
 tensor(0.1467),
 tensor(0.1466),
 tensor(0.1447),
 tensor(0.1446),
 tensor(0.1445),
 tensor(0.1425),
 tensor(0.1425),
 tensor(0.1424),
 tensor(0.1404),
 tensor(0.1403),
 tensor(0.1403),
 tensor(0.1383),
 tensor(0.1382)]

In [14]:
torch.save(model.state_dict(), 'model_weights.pth')

In [15]:
model.state_dict()

OrderedDict([('weights', tensor([0.8523])), ('bias', tensor([0.8260]))])

In [18]:
model.state_dict()

OrderedDict([('weights', tensor([0.8523])), ('bias', tensor([0.8260]))])

In [20]:
model1 = model.load_state_dict(torch.load('model_weights.pth'))
model1.eval()

C:\Users\vikram\AppData\Local\Temp\ipykernel_18728\2771607331.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model1 = model.load_state_dict(torch.load('model_weights.pt

AttributeError: '_IncompatibleKeys' object has no attribute 'eval'

In [22]:
model = LinearRegressionModel()  # Recreate the same model architecture
model.load_state_dict(torch.load('model_weights.pth'))  # Load the weights into it
model.eval()  # Set the model to evaluation mode


C:\Users\vikram\AppData\Local\Temp\ipykernel_18728\1968207754.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model_weights.pth'))  # L

LinearRegressionModel()