In [1]:
import torch

## Rehshaping , stacking , squeezing and unsqueezing tensor

* Reshaping - rehshapes as input to defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple  tensors on top of each other (vstack) or side by side
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze -  add a `1` dimension to target tensor
* Permute - Return a view of the inpit with dimensions permuted in certain way

In [34]:
# create tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [20]:
z = x.view(1, 9)
z.shape

torch.Size([1, 9])

In [23]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [26]:
# stack tensor
x_stack = torch.stack([x, x, x, x],dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [27]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size() 

torch.Size([2, 1, 2, 1, 2])

In [29]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [30]:
y.shape

torch.Size([2, 2, 2])

In [37]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor : {x_reshaped.shape}")

x_squeeze = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeeze}")
print(f"new shape:{x_squeeze.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor : torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape:torch.Size([9])


In [44]:
print(f"previous target : {x_squeeze}")
print(f"\npreviious shape : {x_squeeze.shape}")

x_unsqueezed = x_squeeze.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

previous target : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

previious shape : torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [46]:
# torch.permute - rearrange the dimensions of target pf a target tensor in a specify order

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color channels]

x_permuted = x_original.permute(2, 0, 1) # shift axis 0 ->1, 1->2, 2->0

print(f"Previous target : {x_original.shape}")
print(f"\nNew shape:{x_permuted.shape}")

Previous target : torch.Size([224, 224, 3])

New shape:torch.Size([3, 224, 224])
