In [1]:
import torch

## Tensor Operations

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
  

In [2]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [3]:
# Multiplication tensor by 10
tensor * 10


tensor([10, 20, 30])

In [4]:
# Subtract

tensor - 10

tensor([-9, -8, -7])

In [5]:
# Try uot Pytorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [6]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [7]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [8]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

## Matrix Multiplication

In [9]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: total: 15.6 ms
Wall time: 3.73 ms


In [10]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 5.51 ms


tensor(14)

In [11]:
torch.matmul(torch.rand(3, 2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [12]:
torch.matmul(torch.rand(2, 3), torch.rand(3,2))

tensor([[1.0789, 0.1264],
        [1.1606, 0.1318]])

In [13]:
torch.matmul(torch.rand(3, 10), torch.rand(10,3)).shape

torch.Size([3, 3])

## One of the most common errors in deep learning : shape errors

In [15]:
tensor_A = torch.tensor([[1, 2],
                         [3,4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [17]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issue,We can manipulate the shape of one of our tensor using a **transpose**. A **transpose** switches the axes or dimensions of giiven tensor

In [19]:
tensor_B.T.shape

torch.Size([2, 3])

In [20]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean and sum of tensor (tensor aggregation)

In [21]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [24]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [30]:
torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [31]:
torch.sum(x)

tensor(450)

## indexing (selection data from tensors)
Indexing with pythorch is similar to index with Numpy.

In [6]:
import torch 
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [7]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x[0, 2]

tensor([7, 8, 9])

In [22]:
x[0, 2, 2]

tensor(9)

In [23]:
x[:,1]

tensor([[4, 5, 6]])

In [27]:
x[:, :, 2 ]

tensor([[3, 6, 9]])

In [30]:
x[:, 1, 1]

tensor([5])

In [37]:
x[0, 2, :]

tensor([7, 8, 9])

In [43]:
x[0, :,2], x[:, :, 2]

(tensor([3, 6, 9]), tensor([[3, 6, 9]]))

## Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.
And because of this , Pytorch has functionality to interact with it.
* Data in NumPy, want in Pytorch tensor --> `torch.from_numpy(narray)`
* Pytorch tensor -- > `torch.Tensor.numpy`

In [47]:
# Numpy array to tensor
import numpy as np


arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
# tensor to numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [49]:
numpy_tensor.dtype

dtype('float32')

In [50]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))