In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.DataFrame({"Data": [1, 2, 3 ,4 ,5 ,6 , np.nan, 8, 9, 10]})
df

Data
0   1.0
1   2.0
2   3.0
3   4.0
4   5.0
5   6.0
6   NaN
7   8.0
8   9.0
9  10.0

In [4]:
df.isnull().sum()

Data    1
dtype: int64

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
mean_imp = SimpleImputer(strategy='mean')

In [7]:
mean_imp.fit_transform(df)

array([[ 1.        ],
       [ 2.        ],
       [ 3.        ],
       [ 4.        ],
       [ 5.        ],
       [ 6.        ],
       [ 5.33333333],
       [ 8.        ],
       [ 9.        ],
       [10.        ]])

In [8]:
median_imp = SimpleImputer(strategy='median')

In [9]:
median_imp.fit_transform(df)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 5.],
       [ 8.],
       [ 9.],
       [10.]])

In [10]:
imp_mode = SimpleImputer(strategy="most_frequent")

In [11]:
imp_mode.fit_transform(df)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 1.],
       [ 8.],
       [ 9.],
       [10.]])

In [12]:
con_imp = SimpleImputer(strategy='constant', fill_value=7)

In [13]:
con_imp.fit_transform(df)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [14]:
names = pd.DataFrame({'name':["vikram", 'dharun', 'dhina', np.nan, 'kishore']})
names

name
0   vikram
1   dharun
2    dhina
3      NaN
4  kishore

In [15]:
imp_name = SimpleImputer(strategy = 'constant', fill_value='babe')

In [16]:
imp_name.fit_transform(names)

array([['vikram'],
       ['dharun'],
       ['dhina'],
       ['babe'],
       ['kishore']], dtype=object)

In [17]:
imp_mean_marked = SimpleImputer(strategy='mean', add_indicator=True)

In [18]:
imp_mean_marked.fit_transform(df)

array([[ 1.        ,  0.        ],
       [ 2.        ,  0.        ],
       [ 3.        ,  0.        ],
       [ 4.        ,  0.        ],
       [ 5.        ,  0.        ],
       [ 6.        ,  0.        ],
       [ 5.33333333,  1.        ],
       [ 8.        ,  0.        ],
       [ 9.        ,  0.        ],
       [10.        ,  0.        ]])

In [19]:
df = pd.read_csv("my_csv.csv")
df

Unnamed: 0      Name  miles
0           0      Ryan   50.0
1           1     Nolan   62.0
2           2    Walter    NaN
3           3     Honus  100.0
4           4   Christy   26.0
5           5       NaN   13.0
6           6  Napolean   31.0
7           7      Tris   50.0

In [20]:
from sklearn.compose import make_column_transformer

In [22]:
ct =make_column_transformer(
                        (imp_name,['Name']),
                        (mean_imp,['miles']),
    remainder = 'drop'
)

In [23]:
ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='babe',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['miles'])])

In [24]:
df = ct.fit_transform(df)

In [25]:
df

simpleimputer-1__Name  simpleimputer-2__miles
0                  Ryan               50.000000
1                 Nolan               62.000000
2                Walter               47.428571
3                 Honus              100.000000
4               Christy               26.000000
5                  babe               13.000000
6              Napolean               31.000000
7                  Tris               50.000000