# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(7,7)
tensor_1

tensor([[0.6822, 0.9180, 0.8195, 0.8144, 0.5085, 0.0336, 0.0957],
        [0.3385, 0.5394, 0.4242, 0.2762, 0.9300, 0.9354, 0.9806],
        [0.8922, 0.5017, 0.5698, 0.5588, 0.5279, 0.1755, 0.2275],
        [0.3968, 0.8893, 0.3686, 0.4041, 0.5301, 0.5769, 0.1961],
        [0.4785, 0.9165, 0.3065, 0.6212, 0.1586, 0.0040, 0.1332],
        [0.5314, 0.8773, 0.8517, 0.3181, 0.2846, 0.3629, 0.5912],
        [0.7877, 0.0061, 0.6114, 0.9734, 0.7012, 0.7586, 0.2609]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor = torch.rand(1,7)
tensor1 = torch.rand(1,7)
print(tensor)
print(tensor1)
# Perform matrix multiplication 

matrix = torch.mm(tensor, tensor1.T)
print(matrix)


tensor([[0.9094, 0.4269, 0.8024, 0.6233, 0.4179, 0.4420, 0.0349]])
tensor([[0.3582, 0.2859, 0.5134, 0.8180, 0.6370, 0.0238, 0.2338]])
tensor([[1.6545]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
seed = 1
torch.manual_seed(seed)
tensor = torch.rand(7,1)
torch.manual_seed(seed)
tensor1 = torch.rand(7,1)

# Matrix multiply tensor
mat = torch.mm(tensor, tensor1.T)
mat


tensor([[0.5740, 0.2116, 0.3054, 0.5566, 0.0222, 0.6060, 0.3009],
        [0.2116, 0.0780, 0.1126, 0.2052, 0.0082, 0.2234, 0.1109],
        [0.3054, 0.1126, 0.1625, 0.2961, 0.0118, 0.3224, 0.1601],
        [0.5566, 0.2052, 0.2961, 0.5398, 0.0215, 0.5876, 0.2918],
        [0.0222, 0.0082, 0.0118, 0.0215, 0.0009, 0.0234, 0.0116],
        [0.6060, 0.2234, 0.3224, 0.5876, 0.0234, 0.6398, 0.3177],
        [0.3009, 0.1109, 0.1601, 0.2918, 0.0116, 0.3177, 0.1577]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [66]:
# Set random seed on the GPU
seed = 1234
tensor = torch.cuda.manual_seed(seed)
tensor



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
seed = 42
device = "cuda" if torch.cuda.is_available() else "CPU"


# Check for access to GPU

# Create two random tensors on GPU

tensor = torch.rand(2,2).to(device)
tensor1 = torch.rand(2,2).to(device)
print("Device: ",device)
print(tensor)
print(tensor1)

Device:  cuda
tensor([[0.7718, 0.0112],
        [0.8100, 0.6397]], device='cuda:0')
tensor([[0.9743, 0.8300],
        [0.0444, 0.0246]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [46]:
# Perform matmul on tensor_A and tensor_B

tensor_A = torch.rand(2,2)
tensor_B = torch.rand(2,2)
tensor_C = torch.rand(2,2)
tensor_D = torch.rand(2,2)
tensor_E = torch.rand(2,2)
tensor_F = torch.rand(2,2)

m1 = torch.mm(tensor_A, tensor_B).to(device)
m2 = torch.mm(tensor_C, tensor_D).to(device)
m3 = torch.mm(tensor_E, tensor_F).cuda()
print(m1, m1.shape)
print(m2, m2.shape)
print(m3, m3.shape)

tensor([[0.2130, 0.1142],
        [0.3237, 0.1812]], device='cuda:0') torch.Size([2, 2])
tensor([[0.5351, 0.5209],
        [0.4846, 0.3756]], device='cuda:0') torch.Size([2, 2])
tensor([[0.1573, 0.1358],
        [0.9151, 0.6419]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [54]:
x = torch.arange(0,7)
x

# Find max
print("max: ",x.max(), max(x))


# Find min
print("Min:", x.min(), min(x))

max:  tensor(6) tensor(6)
Min: tensor(0) tensor(0)


### 9. Find the maximum and minimum index values of the output of 7.

In [57]:
# Find arg max
print(x.argmax())

# Find arg min
print(x.argmin())


tensor(6)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [65]:
# Set seed
seed = 7


# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
tensor


# Remove single dimensions
squeezing = torch.squeeze(tensor)
squeezing


# Print out tensors and their shapes
print(squeezing, squeezing.shape)


tensor([0.2636, 0.9967, 0.5107, 0.8953, 0.6219, 0.9482, 0.7885, 0.2451, 0.8512,
        0.5032]) torch.Size([10])
