## Reproducibility(trying the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representationsof data -> again -> again....`

To reduce the randomness in neural networds and pytorch comes the concept of a **random seed**

Essentially what the random seed does is **'flavour'** the randomness



  

In [1]:
import torch

In [2]:
torch.rand(3,3)

tensor([[0.7931, 0.4930, 0.8992],
        [0.4617, 0.2516, 0.4796],
        [0.0454, 0.8956, 0.0061]])

In [3]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7844, 0.6278, 0.4665, 0.9007],
        [0.7751, 0.0010, 0.2175, 0.4713],
        [0.6712, 0.2468, 0.5654, 0.8581]])
tensor([[0.6350, 0.1924, 0.2471, 0.3659],
        [0.6242, 0.6294, 0.8469, 0.9411],
        [0.5663, 0.5228, 0.2379, 0.6821]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [4]:
# let's make some random but reproducible tensor

RANDOM_SEED  = 42
torch.manual_seed(RANDOM_SEED)
radnom_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(radnom_tensor_C)
print(random_tensor_D)
print(radnom_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Different ways of accessing a Gpu in Pytorch

In [5]:
! nvidia-smi

Thu May 29 14:16:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.02                 Driver Version: 576.02         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              6W /   60W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#

In [6]:
torch.cuda.is_available()

True

In [8]:
# setub device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [9]:
torch.cuda.device_count()

1

## Setting up device agnostic code and putting tensors on and off the Gpu

The reason we wnat our tensors/models on the Gpu is Because using a GPU results in faster computations

In [17]:
tensor = torch.tensor([1, 2, 3]) 

# Tensor not on GPU
print(tensor.to(device))
print(tensor.device)

tensor([1, 2, 3], device='cuda:0')
cpu


In [12]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to the CPU

`tensor_on_gpu.numpy()`

`---------------------------------------------------------------------------`
`TypeError`                                `Traceback (most recent call last)`
`Cell In[19], line 1`
`----> 1 tensor_on_gpu.numpy()`

`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

In [19]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [22]:
# to fix the GPU tensor with NUmpy issue, We can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [25]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')