In [1]:
import torch

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [9]:
matrix = torch.tensor([[7, 8],
                      [9, 2]])

matrix

tensor([[7, 8],
        [9, 2]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([[[1, 2, 3],
                       [4, 5, 6 ],
                       [7, 8 ,9 ]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
tensor.ndim

3

### Random tensor

In [24]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.6276, 0.8393, 0.2423, 0.1611],
         [0.9289, 0.4438, 0.6982, 0.1502],
         [0.0445, 0.5421, 0.5559, 0.1647]]])

In [25]:
random_tensor.shape

torch.Size([1, 3, 4])

In [26]:
random_tensor.ndim

3

In [27]:
# create a random tensor size (224, 224, 3)

random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Create a tensor Zeros and ones 

In [31]:
zeros = torch.zeros(size=(3 ,4 ))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(size = (3, 4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Create a range for 0 to 10

In [4]:
ten = torch.arange(start = 1, end= 11, step=1)
ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
zeros_to_ten = torch.arange(0 , 10)

zeros_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tensor Datatypes

In [42]:
float_32_tensor = torch.tensor([1., 2., 3.],dtype=torch.float64, device='cuda', requires_grad=False)
float_32_tensor.dtype

torch.float64

In [43]:
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)

In [45]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)